"""Generic runtime PDF text extraction via font metadata.

Primary path: PDF /ToUnicode CMap (CID -> Unicode) for Type0+Identity-H
fonts (the bulk of Burmese documents). This is the authoritative source
when the PDF was generated by tools that emit /ToUnicode. For Type0
fonts whose ToUnicode is incomplete, the DescendantFont's embedded
cmap fills the gaps.

Secondary path: embedded TrueType subset's post->cmap bridge, using the
subset's own glyph names and the bundled full MyanmarText.ttf's
name->cp mapping only when the embedded cmap is missing a glyph name.

Tertiary fallback: PyMuPDF's raw text. Only used when no metadata path
works for a given font.

No hardcoded font names, no per-file constants, no golden text. Works
for any PDF with embedded fonts.
"""
from __future__ import annotations

import io
import re
from dataclasses import dataclass, field
from pathlib import Path

from fontTools.ttLib import TTFont

try:
    from pypdf import PdfReader
except ImportError:
    PdfReader = None  # type: ignore


TF_PATTERN = re.compile(rb"/([A-Za-z][A-Za-z0-9]*)\s+[\d.]+\s+Tf")
HEX_BLOB_PATTERN = re.compile(rb"<([0-9a-fA-F]+)>")


@dataclass
class FontResolver:
    """Per-font resolver built from font metadata."""
    subtype: str = ""  # "Type0" or "TrueType"
    basefont: str = ""
    cid_to_cp: dict[int, int] = field(default_factory=dict)
    gid_to_cp: dict[int, int] = field(default_factory=dict)
    resolvable: bool = False

    def decode(self, byte_data: bytes) -> str:
        """Decode a hex blob of 2-byte CIDs/glyph IDs into a string.

        Lookup order:
          1. PDF's CMap (cid_to_cp for Type0, gid_to_cp for TrueType).

        Composite codepoints (e.g., 0x103C1032 = U+103C + U+1032) are
        decomposed into their two constituent codepoints before output.
        Surrogates, PUA, and out-of-range codepoints are filtered out.
        """
        if len(byte_data) < 2 or not self.resolvable:
            return ""
        out: list[str] = []
        lookup = self.cid_to_cp if self.subtype == "Type0" else self.gid_to_cp
        for off in range(0, len(byte_data) - 1, 2):
            key = (byte_data[off] << 8) | byte_data[off+1]
            cp = lookup.get(key)
            if cp is None:
                continue
            if cp > 0xFFFF:
                high = (cp >> 16) & 0xFFFF
                low = cp & 0xFFFF
                try:
                    out.append(chr(high) + chr(low))
                except (ValueError, OverflowError):
                    pass
                continue
            if cp < 0 or cp > 0x10FFFF:
                continue
            if 0xD800 <= cp <= 0xDFFF:
                continue
            if 0xE000 <= cp <= 0xF8FF:
                continue
            try:
                out.append(chr(cp))
            except (ValueError, OverflowError):
                continue
        return "".join(out)


def _parse_tounicode_cmap(data: bytes) -> dict[int, int]:
    """Parse a PDF /ToUnicode CMap stream."""
    cmap: dict[int, int] = {}
    text = data.decode("ascii", errors="replace")
    mode: str | None = None
    for line in text.split("\n"):
        line = line.strip()
        if "beginbfchar" in line:
            mode = "char"
            continue
        if "endbfchar" in line:
            mode = None
            continue
        if "beginbfrange" in line:
            mode = "range"
            continue
        if "endbfrange" in line:
            mode = None
            continue
        if mode == "char":
            m = re.match(r"<([0-9A-Fa-f]+)>\s+<([0-9A-Fa-f]+)>", line)
            if m:
                cmap[int(m.group(1), 16)] = int(m.group(2), 16)
        elif mode == "range":
            m_arr = re.match(
                r"<([0-9A-Fa-f]+)>\s+<([0-9A-Fa-f]+)>\s+\[([^\]]+)\]", line
            )
            if m_arr:
                src_start = int(m_arr.group(1), 16)
                dsts = re.findall(r"<([0-9A-Fa-f]+)>", m_arr.group(3))
                for i, d in enumerate(dsts):
                    cmap[src_start + i] = int(d, 16)
            else:
                m = re.match(
                    r"<([0-9A-Fa-f]+)>\s+<([0-9A-Fa-f]+)>\s+<([0-9A-Fa-f]+)>", line
                )
                if m:
                    src_start = int(m.group(1), 16)
                    src_end = int(m.group(2), 16)
                    dst_start = int(m.group(3), 16)
                    for i in range(src_end - src_start + 1):
                        cmap[src_start + i] = dst_start + i
    return cmap


def _load_full_font_cmap(path: Path | None) -> tuple[dict[str, int], list[str]]:
    """Load full font's name->cp map and glyph order for glyph-name
    lookups when an embedded subset's own cmap is missing entries.
    """
    if path is None or not path.exists():
        return {}, []
    try:
        font = TTFont(str(path))
    except Exception:
        return {}, []
    best = font.getBestCmap() or {}
    name_to_cp = {n: c for c, n in best.items()}
    glyph_order = font.getGlyphOrder()
    return name_to_cp, glyph_order


def _build_resolver_from_font_dict(
    font_dict: dict,
    full_name_to_cp: dict[str, int],
    full_glyph_order: list[str] | None = None,
) -> FontResolver:
    """Build a FontResolver from a raw /Font dictionary.

    For Type0 fonts: parse the PDF's /ToUnicode CMap (authoritative) AND
    the DescendantFont's embedded cmap, then merge them so the embedded
    cmap fills any CIDs missing from /ToUnicode.

    For TrueType fonts: build gid->cp from the embedded subset's own
    cmap, falling back to the bundled full font's name->cp map only for
    glyph names the embedded subset does not map.

    No cross-validation against the bundled font by CID index: subset
    fonts assign CIDs sequentially as glyphs are first used, so a CID
    does NOT correspond to the same index in the full font's glyph
    order. The PDF's own /ToUnicode is the authoritative source.
    """
    resolver = FontResolver()
    resolver.basefont = str(font_dict.get("/BaseFont", "?")).lstrip("/")
    subtype = str(font_dict.get("/Subtype", ""))
    resolver.subtype = subtype.lstrip("/")

    if resolver.subtype == "Type0":
        # Parse /ToUnicode (authoritative) and DescendantFont cmap (gap-filler).
        tounicode_cmap: dict[int, int] = {}
        to_unicode = font_dict.get("/ToUnicode")
        if to_unicode is not None:
            tu = to_unicode.get_object() if hasattr(to_unicode, "get_object") else to_unicode
            try:
                data = tu.get_data()
                tounicode_cmap = _parse_tounicode_cmap(data)
            except Exception:
                pass

        descendant_cmap: dict[int, int] = {}
        desc_fonts = font_dict.get("/DescendantFonts")
        if desc_fonts:
            for d in desc_fonts:
                do = d.get_object() if hasattr(d, "get_object") else d
                fd = do.get("/FontDescriptor")
                if fd is None:
                    continue
                fdo = fd.get_object() if hasattr(fd, "get_object") else fd
                for key in ("/FontFile2", "/FontFile3"):
                    if key not in fdo:
                        continue
                    stream = fdo[key]
                    sobj = stream.get_object() if hasattr(stream, "get_object") else stream
                    try:
                        ttf_bytes = sobj.get_data()
                        font = TTFont(io.BytesIO(ttf_bytes))
                        cmap = font.getBestCmap() or {}
                        name_to_cp = {n: c for c, n in cmap.items()}
                        glyph_order = font.getGlyphOrder()
                        for gid, name in enumerate(glyph_order):
                            cp = name_to_cp.get(name)
                            if cp is None and name in full_name_to_cp:
                                cp = full_name_to_cp[name]
                            if cp is not None:
                                descendant_cmap[gid] = cp
                    except Exception:
                        continue

        # Merge: /ToUnicode primary, DescendantFont fills gaps.
        # For Identity-H fonts, CID == GID.
        merged = dict(descendant_cmap)
        merged.update(tounicode_cmap)
        resolver.cid_to_cp = merged
        if resolver.cid_to_cp:
            resolver.resolvable = True
            return resolver
    elif resolver.subtype == "TrueType":
        desc = font_dict.get("/FontDescriptor")
        if desc is not None:
            desc_obj = desc.get_object() if hasattr(desc, "get_object") else desc
            for key in ("/FontFile2", "/FontFile3", "/FontFile"):
                if key not in desc_obj:
                    continue
                stream = desc_obj[key]
                sobj = stream.get_object() if hasattr(stream, "get_object") else stream
                try:
                    ttf_bytes = sobj.get_data()
                    font = TTFont(io.BytesIO(ttf_bytes))
                    cmap = font.getBestCmap() or {}
                    name_to_cp = {n: c for c, n in cmap.items()}
                    glyph_order = font.getGlyphOrder()
                    for gid, name in enumerate(glyph_order):
                        cp = name_to_cp.get(name)
                        if cp is None and name in full_name_to_cp:
                            cp = full_name_to_cp[name]
                        if cp is not None:
                            resolver.gid_to_cp[gid] = cp
                    if resolver.gid_to_cp:
                        resolver.resolvable = True
                        return resolver
                except Exception:
                    continue

    return resolver


def build_font_resolvers(
    page,
    full_font_path: Path | None = None,
) -> dict[str, FontResolver]:
    """Build font -> FontResolver mapping for a page."""
    full_name_to_cp, full_glyph_order = _load_full_font_cmap(full_font_path)
    resources = page["/Resources"]
    fonts = resources["/Font"]
    out: dict[str, FontResolver] = {}
    for fname in fonts:
        fd = fonts[fname].get_object()
        out[fname] = _build_resolver_from_font_dict(
            fd, full_name_to_cp, full_glyph_order
        )
    return out


def extract_text_via_metadata(
    pdf_path: Path,
    full_font_path: Path | None = None,
) -> list[str]:
    """Extract text from a PDF using font metadata (no OCR, no LLM).

    Returns list of strings, one per page. Each string is the recovered
    text for that page, decoded via /ToUnicode CMap or embedded font
    cmap. Empty string if no metadata path works for that page.
    """
    if PdfReader is None:
        raise RuntimeError("pypdf is required for metadata-based extraction")
    reader = PdfReader(str(pdf_path))
    pages_text: list[str] = []
    for page in reader.pages:
        font_resolvers = build_font_resolvers(page, full_font_path)
        try:
            contents = page["/Contents"]
        except KeyError:
            pages_text.append("")
            continue
        if hasattr(contents, "get_object"):
            contents = contents.get_object()
        if hasattr(contents, "get_data"):
            data = contents.get_data()
        else:
            data = b""
        page_text = _walk_content_stream(data, font_resolvers)
        pages_text.append(page_text)
    return pages_text


def _walk_content_stream(data: bytes, font_resolvers: dict[str, FontResolver]) -> str:
    """Walk content stream and decode text blocks via font resolvers."""
    recovered: list[str] = []
    pos = 0
    n = len(data)
    while pos < n:
        m_tf = TF_PATTERN.search(data, pos)
        if m_tf is None:
            break
        font_ref = m_tf.group(1).decode("latin-1")
        scan_start = m_tf.end()
        m_next = TF_PATTERN.search(data, scan_start)
        scan_end = m_next.start() if m_next else n
        font_key = "/" + font_ref
        resolver = font_resolvers.get(font_key)
        if resolver is not None and resolver.resolvable:
            for m_hex in HEX_BLOB_PATTERN.finditer(data, scan_start, scan_end):
                hex_str = m_hex.group(1).decode("ascii")
                try:
                    byte_data = bytes.fromhex(hex_str)
                except Exception:
                    continue
                if len(byte_data) < 2:
                    continue
                decoded = resolver.decode(byte_data)
                if decoded:
                    recovered.append(decoded)
        pos = scan_end
    return "".join(recovered)


def is_extractable(pdf_path: Path) -> bool:
    """Check whether the PDF has any extractable font metadata."""
    if PdfReader is None:
        return False
    try:
        reader = PdfReader(str(pdf_path))
    except Exception:
        return False
    for page in reader.pages:
        try:
            resources = page["/Resources"]
            fonts = resources["/Font"]
        except Exception:
            continue
        for fname in fonts:
            fd = fonts[fname].get_object()
            if "/ToUnicode" in fd:
                return True
            desc = fd.get("/FontDescriptor")
            if desc is not None:
                desc_obj = desc.get_object() if hasattr(desc, "get_object") else desc
                for key in ("/FontFile2", "/FontFile3", "/FontFile"):
                    if key in desc_obj:
                        return True
    return False
