"""Frozen 15-slot Brain Framework definition and synonym dictionaries.

The tuple FROZEN_SECTIONS is the canonical ordering and wording.
Never modify it. Section titles use the exact wording from the Brain template.
"""

# Canonical 15 sections, in template order.
FROZEN_SECTIONS: tuple = (
    {"id": 1, "title": "Header"},
    {"id": 2, "title": "Brief Description"},
    {"id": 3, "title": "Approval & Governance"},
    {"id": 4, "title": "Reason for Policy"},
    {"id": 5, "title": "INTRODUCTION"},
    {"id": 6, "title": "POLICY STATEMENT"},
    {"id": 7, "title": "1. Purpose"},
    {"id": 8, "title": "2. Scope & Beneficiaries"},
    {"id": 9, "title": "3. Exclusions"},
    {"id": 10, "title": "4. Award Structure & Payout Tiers"},
    {"id": 11, "title": "Policy Review Note"},
    {"id": 12, "title": "DEFINITIONS"},
    {"id": 13, "title": "RELATED POLICIES, PROCEDURES, FORMS, GUIDELINES & OTHER RESOURCES"},
    {"id": 14, "title": "HISTORY"},
    {"id": 15, "title": "Brain Logo & Image"},
)


# Headers used to detect each section in the INPUT policy.
# Matching is fuzzy (rapidfuzz ratio >= 85) and case-insensitive.
#
# This dictionary is the single source of truth for prose-slot
# heading detection. The RAG layer (policy_platform.rag.heading_anchors)
# pulls from here to build its per-slot heading patterns.
SECTION_HEADING_SYNONYMS: dict[int, list[str]] = {
    1: [
        # Slot 1 is filled by label-row parsing, not heading-anchor.
        # Listed here only for completeness.
        "header",
    ],
    2: [
        "brief description",
        "summary",
        "overview",
        "policy summary",
        "policy overview",
        "executive summary",
    ],
    3: [
        # Slot 3 is filled by label-row parsing (effective date,
        # approved by, etc.). Listed for completeness.
        "approval and governance",
        "approval & governance",
        "governance",
        "approval information",
    ],
    4: [
        "reason for policy",
        "rationale",
        "background",
        "policy rationale",
        "policy background",
        "why this policy",
        "policy context",
    ],
    5: [
        "introduction",
        "background",
        "preamble",
        "overview",
        "policy introduction",
        "executive overview",
    ],
    6: [
        "policy statement",
        "policy statement - purpose",
        "policy statement & purpose",
        "policy statement and purpose",
        "statement of policy",
        "company policy",
        "corporate policy",
    ],
    7: [
        "purpose",
        "aim",
        "aims",
        "objective",
        "objectives",
        "policy objective",
        "policy objectives",
        "policy purpose",
        "intent",
        "policy intent",
        "goals",
        "policy goals",
    ],
    8: [
        "scope",
        "scope & beneficiaries",
        "scope and beneficiaries",
        "scope and applicability",
        "applicability",
        "application",
        "who this policy applies to",
        "applicable to",
        "policy scope",
        "scope of this policy",
        "covered parties",
        "eligible parties",
        "eligibility",
    ],
    9: [
        "exclusions",
        "exclusion",
        "exceptions",
        "exception",
        "exclusions and limitations",
        "limitations",
        "limitation",
        "what is not covered",
        "out of scope",
        "not applicable",
        "excluded",
    ],
    10: [
        "award structure",
        "award structure & payout tiers",
        "award structure and payout tiers",
        "award tiers",
        "payout structure",
        "payout tiers",
        "benefits",
        "entitlements",
        "compensation tiers",
        "recognition levels",
        "tier structure",
        "award levels",
        # Flood / disaster relief policies use these terms.
        "assistance structure",
        "assistance structure and payout tiers",
        "relief structure",
        "flood relief tier",
        "flood relief amount",
        "compensation amount",
        "damage level",
        "damage level payout",
        "emergency assistance structure",
        "support structure",
        # School / facility / building policies use these terms.
        "facility structure",
        "level facility",
        "maintenance level",
        "priority level",
        "facility type",
        "maintenance frequency",
        "service level",
        "service tier",
        # Generic payout terms used in many policies.
        "amount payable",
        "benefit amount",
        "tier amount",
        "payout amount",
        "compensation",
        "reimbursement",
        # Building / facility maintenance tiered funding (school building,
        # hospital building, etc.) — the source heading may use any of
        # these tier/level structures for the maintenance-vs-funding table.
        "maintenance & funding tiers",
        "maintenance and funding tiers",
        "funding tiers",
        "funding structure",
        "funding levels",
        "funding limits",
        "funding level",
        "maintenance tiers",
        "building maintenance tiers",
        "maintenance tier",
        "repair tier",
        "repair tiers",
        "project tier",
        "project tiers",
        "tier funding",
        "tier-based funding",
        "tier based funding",
        "tier criteria",
        "tier eligibility",
        "support tier",
        "support tiers",
        "structure & tiers",
        "structure and tiers",
        "amount tiers",
        "category tier",
        "category tiers",
        "category payout",
        "category structure",
    ],
    11: [
        "policy review note",
        "review note",
        "review notes",
        "review",
        "note",
        "policy notes",
        "review schedule",
    ],
    12: [
        "definitions",
        "definition",
        "defined terms",
        "glossary",
        "terminology",
        "key terms",
        "meaning of terms",
        "key definitions",
        "key definition",
        "main definitions",
        "core definitions",
        "definitions key terms",
    ],
    13: [
        "related policies",
        "related policies, procedures, forms, guidelines & other resources",
        "related policies, procedures, forms, guidelines &",
        "related policies, procedures, forms",
        "related documents",
        "references",
        "related policies and procedures",
        "cross references",
        "associated documents",
        "see also",
        "related materials",
        "for more information",
        "see related",
        "other policies",
        "related",
        "associated policies",
        "linked policies",
        "companion policies",
        "supplementary policies",
        "reference materials",
        "external references",
        "further reading",
    ],
    14: [
        "history",
        "version history",
        "revision history",
        "document history",
        "change log",
        "changelog",
        "v. history",
        "v . history",
        "version log",
        "revision log",
        "document control",
        "amendment history",
    ],
    15: [],  # image slot; never matched from text
}


def is_frozen() -> bool:
    return True
